run:
    signer-file-key-path: testkey.pem
    trace: false
    attestations:
        - git
verify:
    attestations:
        - "test-att.json"
    policy: policy-signed.json
    publickey: testpub.pem